apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h1mvgkhrw-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a29306fc93.iu31.p3.openshiftapps.com/rhtap/rhtap-qe:7f491cce50a6dde1c1e23e3194ccca21b1b21273@sha256:6f79988cc91cf61e6624a14aa8c035c19cea50088c1bcc90fa68c12ca53d6ac7
          name: container-image
