apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: h1mvgkhrw-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/h1mvgkhrw-dotnet-basic-gitops